# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab8de29b9b6a289afbd50b2262833340a8203c517885e1dc129cc9a4e0fc60635ebf86d3b5f5148c871cebc422adf55f0f0d7404c4e0713728556964f9f32cbd

test:
  secret_key_base: b175ae49ecbfc7c6c73fdc0bb2f4eaef8e62882fd2eff6cae41fb8f0fe683ca9335d6f7f45008a24d3d6ada059e09eb42ba9639b1577d38400f0f9ca3d37a1fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
